update snapshots + update scripts to support darwin

diff --git a/scripts/generate-test-data b/scripts/generate-test-data
--- a/scripts/generate-test-data
+++ b/scripts/generate-test-data
@@ -1,7 +1,33 @@
 #!/usr/bin/env bash
+set -euo pipefail
 
-project_path=$(realpath "$(dirname "$0")/..")
+function generate_test_data_linux() {
+    man git-init  | awk '/^SYNOPSIS/,/^DESCRIPTION/ {print}' | head -n -1 | tail -n +2 > "$project_path/test-resources/input/man-git-init.txt"
+    man git-clone | awk '/^SYNOPSIS/,/^DESCRIPTION/ {print}' | head -n -1 | tail -n +2 > "$project_path/test-resources/input/man-git-clone.txt"
+    man git       | awk '/^SYNOPSIS/,/^DESCRIPTION/ {print}' | head -n -1 | tail -n +2 > "$project_path/test-resources/input/man-git.txt"
+}
 
-man git-init  | awk '/^SYNOPSIS/,/^DESCRIPTION/ {print}' | head -n -1 | tail -n +2 > "$project_path/test-resources/input/man-git-init.txt"
-man git-clone | awk '/^SYNOPSIS/,/^DESCRIPTION/ {print}' | head -n -1 | tail -n +2 > "$project_path/test-resources/input/man-git-clone.txt"
-man git       | awk '/^SYNOPSIS/,/^DESCRIPTION/ {print}' | head -n -1 | tail -n +2 > "$project_path/test-resources/input/man-git.txt"
+function generate_test_data_darwin() {
+    man git-init  | col -bx | awk '/^SYNOPSIS/,/^DESCRIPTION/ {print}' | ghead -n -1 | tail -n +2 > "$project_path/test-resources/input/man-git-init.txt"
+    man git-clone | col -bx | awk '/^SYNOPSIS/,/^DESCRIPTION/ {print}' | ghead -n -1 | tail -n +2 > "$project_path/test-resources/input/man-git-clone.txt"
+    man git       | col -bx | awk '/^SYNOPSIS/,/^DESCRIPTION/ {print}' | ghead -n -1 | tail -n +2 > "$project_path/test-resources/input/man-git.txt"
+}
+
+function main() {
+    local project_path=$(realpath "$(dirname "$0")/..")
+    local os_name="$(uname)"
+    if [[ $os_name == "Darwin" && ! "$(which "ghead" 2>/dev/null)" ]]; then
+        echo "\"coreutils\" not installed - \"ghead\" command missing" >&2
+        return 1
+    fi
+    if [[ $os_name == "Linux" ]]; then
+        generate_test_data_linux
+    elif [[ $os_name == "Darwin" ]]; then
+        generate_test_data_darwin
+    else
+        echo "Unsupported OS detected" 1>&2
+        return 1
+    fi
+}
+
+main "$@"
diff --git a/scripts/regenerate-snapshots b/scripts/regenerate-snapshots
--- a/scripts/regenerate-snapshots
+++ b/scripts/regenerate-snapshots
@@ -1,12 +1,37 @@
 #!/usr/bin/env bash
 
-project_path=$(realpath "$(dirname "$0")/..")
-project_executable="$project_path/bin/synopsis-parser"
-if [[ ! -x $project_executable ]];then
-    echo "Project not build" >&2
-    exit 1
-fi
+function regenerate_snapshots_linux() {
+    man git-init  | awk '/^SYNOPSIS/,/^DESCRIPTION/ {print}' | head -n -1 | tail -n +2 | "$project_executable" > "$project_path/test-resources/__snapshots/git-init.json"
+    man git-clone | awk '/^SYNOPSIS/,/^DESCRIPTION/ {print}' | head -n -1 | tail -n +2 | "$project_executable" > "$project_path/test-resources/__snapshots/git-clone.json"
+    man git       | awk '/^SYNOPSIS/,/^DESCRIPTION/ {print}' | head -n -1 | tail -n +2 | "$project_executable" > "$project_path/test-resources/__snapshots/git.json"
+}
 
-man git-init  | awk '/^SYNOPSIS/,/^DESCRIPTION/ {print}' | head -n -1 | tail -n +2 | "$project_executable" > "$project_path/test-resources/__snapshots/git-init.json"
-man git-clone | awk '/^SYNOPSIS/,/^DESCRIPTION/ {print}' | head -n -1 | tail -n +2 | "$project_executable" > "$project_path/test-resources/__snapshots/git-clone.json"
-man git       | awk '/^SYNOPSIS/,/^DESCRIPTION/ {print}' | head -n -1 | tail -n +2 | "$project_executable" > "$project_path/test-resources/__snapshots/git.json"
+function regenerate_snapshots_darwin() {
+    man git-init  | col -bx | awk '/^SYNOPSIS/,/^DESCRIPTION/ {print}' | ghead -n -1 | tail -n +2 | "$project_executable" > "$project_path/test-resources/__snapshots/git-init.json"
+    man git-clone | col -bx | awk '/^SYNOPSIS/,/^DESCRIPTION/ {print}' | ghead -n -1 | tail -n +2 | "$project_executable" > "$project_path/test-resources/__snapshots/git-clone.json"
+    man git       | col -bx | awk '/^SYNOPSIS/,/^DESCRIPTION/ {print}' | ghead -n -1 | tail -n +2 | "$project_executable" > "$project_path/test-resources/__snapshots/git.json"
+}
+
+function main() {
+    local project_path=$(realpath "$(dirname "$0")/..")
+    local project_executable="$project_path/bin/synopsis-parser"
+    local os_name="$(uname)"
+    if [[ ! -x $project_executable ]];then
+        echo "Project not build" >&2
+        return 1
+    fi
+    if [[ $os_name == "Darwin" && ! "$(which "ghead" 2>/dev/null)" ]]; then
+        echo "\"coreutils\" not installed - \"ghead\" command missing" >&2
+        return 1
+    fi
+    if [[ $os_name == "Linux" ]]; then
+        regenerate_snapshots_linux
+    elif [[ $os_name == "Darwin" ]]; then
+        regenerate_snapshots_darwin
+    else
+        echo "Unsupported OS detected" 1>&2
+        return 1
+    fi
+}
+
+main "$@"
